version: '3.1'
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - "./src/main/resources/data:/docker-entrypoint-initdb.d" # init script
    environment:
      MYSQL_DATABASE: eazybank
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
